/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChallansRouteImport } from './routes/_authenticated/challans'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedChallansIndexRouteImport } from './routes/_authenticated/challans.index'
import { Route as AuthenticatedChallansIdRouteImport } from './routes/_authenticated/challans.$id'
import { Route as AuthenticatedChallansCreateRouteImport } from './routes/_authenticated/challans.create'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChallansRoute = AuthenticatedChallansRouteImport.update({
  id: '/challans',
  path: '/challans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallansIndexRoute =
  AuthenticatedChallansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChallansRoute,
  } as any)
const AuthenticatedChallansIdRoute = AuthenticatedChallansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChallansRoute,
} as any)
const AuthenticatedChallansCreateRoute =
  AuthenticatedChallansCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedChallansRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challans': typeof AuthenticatedChallansRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/products': typeof AuthenticatedProductsRoute
  '/challans/$id': typeof AuthenticatedChallansIdRoute
  '/challans/create': typeof AuthenticatedChallansCreateRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/challans/': typeof AuthenticatedChallansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/products': typeof AuthenticatedProductsRoute
  '/challans/$id': typeof AuthenticatedChallansIdRoute
  '/challans/create': typeof AuthenticatedChallansCreateRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/challans': typeof AuthenticatedChallansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/challans': typeof AuthenticatedChallansRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/challans/$id': typeof AuthenticatedChallansIdRoute
  '/_authenticated/challans/create': typeof AuthenticatedChallansCreateRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/challans/': typeof AuthenticatedChallansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challans'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/products'
    | '/challans/$id'
    | '/challans/create'
    | '/customers/$id'
    | '/challans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/products'
    | '/challans/$id'
    | '/challans/create'
    | '/customers/$id'
    | '/challans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/challans'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/products'
    | '/_authenticated/challans/$id'
    | '/_authenticated/challans/create'
    | '/_authenticated/customers/$id'
    | '/_authenticated/challans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/challans': {
      id: '/_authenticated/challans'
      path: '/challans'
      fullPath: '/challans'
      preLoaderRoute: typeof AuthenticatedChallansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challans/': {
      id: '/_authenticated/challans/'
      path: '/'
      fullPath: '/challans/'
      preLoaderRoute: typeof AuthenticatedChallansIndexRouteImport
      parentRoute: typeof AuthenticatedChallansRoute
    }
    '/_authenticated/challans/$id': {
      id: '/_authenticated/challans/$id'
      path: '/$id'
      fullPath: '/challans/$id'
      preLoaderRoute: typeof AuthenticatedChallansIdRouteImport
      parentRoute: typeof AuthenticatedChallansRoute
    }
    '/_authenticated/challans/create': {
      id: '/_authenticated/challans/create'
      path: '/create'
      fullPath: '/challans/create'
      preLoaderRoute: typeof AuthenticatedChallansCreateRouteImport
      parentRoute: typeof AuthenticatedChallansRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
  }
}

interface AuthenticatedChallansRouteChildren {
  AuthenticatedChallansIdRoute: typeof AuthenticatedChallansIdRoute
  AuthenticatedChallansCreateRoute: typeof AuthenticatedChallansCreateRoute
  AuthenticatedChallansIndexRoute: typeof AuthenticatedChallansIndexRoute
}

const AuthenticatedChallansRouteChildren: AuthenticatedChallansRouteChildren = {
  AuthenticatedChallansIdRoute: AuthenticatedChallansIdRoute,
  AuthenticatedChallansCreateRoute: AuthenticatedChallansCreateRoute,
  AuthenticatedChallansIndexRoute: AuthenticatedChallansIndexRoute,
}

const AuthenticatedChallansRouteWithChildren =
  AuthenticatedChallansRoute._addFileChildren(
    AuthenticatedChallansRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChallansRoute: typeof AuthenticatedChallansRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChallansRoute: AuthenticatedChallansRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
